version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bloodbank
    ports:
      - "3307:3306"

  backend:
    build: ./BloodBankManagement
    container_name: hemo-backend
    depends_on:
      - mysql
    ports:
      - "8081:8080"
    restart: always
